#!/bin/sh
if [[ $# -lt 1 ]] 
then 
  echo Need to specify search text
else 
  printf "\e[34m⌘+Click will open the file:\e[0m"
  echo
  oldIFS="$IFS"
  IFS='*'
  find ~/BOOKS -type f -iname "*$**"
  IFS=$oldIFS
fi
