#!/bin/sh
# findbook for macOS: by Soomin K.
# 1. Gives an example of the regex syntax for macOS
# 2. Use find to list and rg to highlight the keywords given as arguments

###################### Set the root directory for the book files
PATH_BOOKS=~/BOOKS
######################
# declarations for the template (example) strings
ex_find=
ex_rg=
ex_str=

# color definitions
C_R='\e[31m'
C_G='\e[32m'
C_B='\e[34m'
C_Y='\e[33m'
C_N='\e[0m'

print_path()
{
  printf "${C_G}"
  ls ${PATH_BOOKS}
}

if [[ $# -lt 1 ]]; then
  print_path
  printf "${C_N}fb - findbook utility: ${C_R}Need to specify search text as arguments (AND conditions)${C_N} or ⌘v to paste the example.\n"
  ex_find="geometry.*physics"
  ex_rg="geometry|physics"
else
  for a in "$@"; do
    if [[ -z $ex_find ]]; then
      ex_find="$a"
      ex_rg="$a"
    else
      ex_find="$ex_find.*$a"
      ex_rg="$ex_rg|$a"
    fi
  done
  # IFS: Internal Field Separator - how to do word splitting
  oldIFS="$IFS"
  # to replace whitespaces with * for the find search pattern
  IFS='*'
  ###################################################
  res=`find "${PATH_BOOKS}" -type f -iname "*$**"`  # -type d  for directory
  ###################################################
  if [[ -z $res ]]; then
    print_path
    printf "${C_R}No matching results found.${C_N} "
  else
    # to replace whitespaces with | (or) for the rg search pattern
    IFS='|'
    echo $res | rg -i "$*"
    printf "${C_B}⌘click to open the file.${C_N} "
  fi
  IFS=$oldIFS
fi
# copy to the clipboard with no color code, so that the user can paste to edit, using ripgrep just for highlighting
printf "find -E /Users/smk/BOOKS -type f -iregex \".*($ex_find).*\" | rg -i \"$ex_rg\"" | pbcopy
# now print with color
printf "${C_Y}find${C_N} ${C_G}-E${C_N} ${PATH_BOOKS} -type f ${C_G}-iregex${C_N} \".*(${C_B}${ex_find}${C_N}).*\" | ${C_Y}rg${C_N} -i \"${C_B}${ex_rg}${C_N}\"\n"
