#!/bin/zsh
# listvimsessions: by Soomin K.
# List vim sessions and copy the command to the clipboard
# color definitions
C_R='\e[31m'
C_G='\e[32m'
C_B='\e[34m'
C_Y='\e[33m'
C_N='\e[0m'
DATE=`date`
VCMD="v -S ~/.vim/sess/" 
print "${C_Y}List Vim Sessions${C_G} ${DATE}${C_N}"
ls -l ~/.vim/sess/
printf ${VCMD} | pbcopy
print "${C_B}⌘v to paste the vim command${C_G} ${VCMD}${C_N}"
