#!/bin/sh
C_R='\e[0;31m'
C_G='\e[0;32m'
C_B='\e[0;34m'
C_Y='\e[0;33m'
C_N='\e[0m'

################## Set the session folder for vim
SESSION_DIR=~/.vim/sessions
##################
print "${C_G}${SESSION_DIR}${C_N}"
ls -l ${SESSION_DIR}
printf "v -S ${SESSION_DIR}/" | pbcopy
