#!/bin/zsh
RED='\e[0;31m'
GREEN='\e[0;32m'
BLUE='\e[0;34m'
YELLOW='\e[0;33m'
BK='\e[0;30m'
DG='\e[1;30m'
NC='\e[0m'
SP='\e[1;34m'
TM='\e[1;32m'
QC='\e[1;35m'
SY='\e[0;36m'
DC='\e[0;35m'
DATE=`date +"%a %B %d (%m/%d/%Y)"`
TIME=`date +"%H:%M:%S"`
print "${SP}╔═╗┌─┐┌─┐┌─┐┌─┐${TM}┌┬┐┬┌┬┐┌─┐${QC}╔═╗"
print "${SP}╚═╗├─┘├─┤│  ├┤ ${TM} │ ││││├┤ ${QC}║═╬╗"
print "${SP}╚═╝┴  ┴ ┴└─┘└─┘${TM} ┴ ┴┴ ┴└─┘${QC}╚═╝╚${DG} Inc, Yokohama & CA 94583, Since 01/07/2019${NC}"
print "${SY}███████╗██╗   ██╗███╗   ███╗██████╗  ██████╗ ██╗     ██╗ ██████╗${DC}██████╗ ██████╗"
print "${SY}██╔════╝╚██╗ ██╔╝████╗ ████║██╔══██╗██╔═══██╗██║     ██║██╔════╝${DC}╚════██╗██╔══██╗"
print "${SY}███████╗ ╚████╔╝ ██╔████╔██║██████╔╝██║   ██║██║     ██║██║     ${DC} █████╔╝██║  ██║"
print "${SY}╚════██║  ╚██╔╝  ██║╚██╔╝██║██╔══██╗██║   ██║██║     ██║██║     ${DC} ╚═══██╗██║  ██║"
print "${SY}███████║   ██║   ██║ ╚═╝ ██║██████╔╝╚██████╔╝███████╗██║╚██████╗${DC}██████╔╝██████╔╝"
print "${SY}╚══════╝   ╚═╝   ╚═╝     ╚═╝╚═════╝  ╚═════╝ ╚══════╝╚═╝ ╚═════╝${DC}╚═════╝ ╚═════╝${NC}"
print "${DG}Spacetime and Symbolic Evolution${BK} to Singularity ${RED}The Pleasure of the Text${NC}"
print "${GREEN}${TIME} ${YELLOW}${DATE} ${QC}*****${NC}"
cal -3
uptime
print "${GREEN}TDL: ${NC}Clockwork, Calendar, "
