#!/bin/zsh
###########################################
# Splash Screen: Logo (/etc/motd for MacBook)
# by Soomin K.
###########################################
# ~/z/dev/versions
C_R='\e[0;31m'
C_G='\e[0;32m'
C_B='\e[0;34m'
C_Y='\e[0;33m'
C_N='\e[0m'
BBK='\e[49m'
BLBK='\e[44m'
CYBK='\e[46m'
YBK='\e[43m'
BK='\e[0;30m'
WH='\e[0;39m'
DG='\e[1;30m'
SP='\e[1;34m'
TM='\e[1;32m'
QC='\e[1;35m'
SY='\e[0;36m'
DC='\e[0;35m'
for i in {232..255} {255..232}; do printf "\e[48;5;${i}m \e[0m"; done; echo
print " ${SP}╔═╗┌─┐┌─┐┌─┐┌─┐${TM}┌┬┐┬┌┬┐┌─┐${QC}╔═╗ ${DG} INC"
print " ${SP}╚═╗├─┘├─┤│  ├┤ ${TM} │ ││││├┤ ${QC}║═╬╗${DG} Yokohama & CA 94583"
print " ${SP}╚═╝┴  ┴ ┴└─┘└─┘${TM} ┴ ┴┴ ┴└─┘${QC}╚═╝╚${DG} Since 01/07/2019${C_N}"
for i in {232..255} {255..232}; do printf "\e[48;5;${i}m \e[0m"; done; echo
print "${SY}███████╗██╗   ██╗███╗   ███╗██████╗  ██████╗ ██╗     ██╗ ██████╗${DC}██████╗ ██████╗"
print "${SY}██╔════╝╚██╗ ██╔╝████╗ ████║██╔══██╗██╔═══██╗██║     ██║██╔════╝${DC}╚════██╗██╔══██╗"
print "${SY}███████╗ ╚████╔╝ ██╔████╔██║██████╔╝██║   ██║██║     ██║██║     ${DC} █████╔╝██║  ██║"
print "${SY}╚════██║  ╚██╔╝  ██║╚██╔╝██║██╔══██╗██║   ██║██║     ██║██║     ${DC} ╚═══██╗██║  ██║"
print "${SY}███████║   ██║   ██║ ╚═╝ ██║██████╔╝╚██████╔╝███████╗██║╚██████╗${DC}██████╔╝██████╔╝"
print "${SY}╚══════╝   ╚═╝   ╚═╝     ╚═╝╚═════╝  ╚═════╝ ╚══════╝╚═╝ ╚═════╝${DC}╚═════╝ ╚═════╝${C_N}"
print "${DG}Spacetime and Symbolic Evolution${BK} to Singularity ${C_R}The Pleasure of the Text 📖${C_N}"
printf "🌏 "
UPTM=`uptime`
MOON=`curl -s 'wttr.in/Yokohama?format=%m%M'`
print "${C_B}${UPTM}${C_N} ${MOON}"
DST="${C_N}    "
WTTR=`curl -s 'wttr.in/Yokohama?format=+%c+%t💧%h'`
CITY=`TZ=":Asia/Tokyo"          date +"%H:%M:%S %a %B %d %Y Yokohama      (UTC+9)"`
print "🗼 ${BK}${YBK}${CITY}${DST} ${C_N}${WTTR}"
DST="${C_N}🔅${C_Y}+1${C_N}"
WTTR=`curl -s 'wttr.in/Paris?format=+%c+%t💧%h'`
CITY=`TZ=":Europe/Paris"        date +"%H:%M:%S %a %B %d %Y Paris         (UTC+1)"`
print "🇫🇷  ${C_R}${CITY}${DST} ${C_N}${WTTR}"
WTTR=`curl -s 'wttr.in/New York?format=+%c+%t💧%h'`
CITY=`TZ=":America/New_York"    date +"%H:%M:%S %a %B %d %Y New York      (UTC-5)"`
print "🗽 ${C_G}${CITY}${DST} ${C_N}${WTTR}"
WTTR=`curl -s 'wttr.in/San Francisco?format=+%c+%t💧%h'`
CITY=`TZ=":America/Los_Angeles" date +"%H:%M:%S %a %B %d %Y San Francisco (UTC-8)"`
print "❤️  ${BK}${BLBK}${CITY}${DST} ${C_N}${WTTR}"
cal -3
printf "🔥 ${C_G}TDL: ${C_N}Web Utilities "
printf "💰${C_G}{${C_N}Game,${C_G}Education${C_N},${C_B}Finance${C_N},"
print  "${C_R}Messaging${C_N},${C_Y}Movies${C_G}}${C_N}"
