#!/bin/zsh
C_R='\e[0;31m'
C_G='\e[0;32m'
C_B='\e[0;34m'
C_Y='\e[0;33m'
C_N='\e[0m'

runCmd ()
{
  printf $1
  if [ -z $3 ]; then     # just print info
    print "${C_B} $2${C_N}"
  else                   # run command
    print "${C_G} $2 ${C_B}$3${C_N}"
    $2 $3
  fi
}
~/z/dev/logo
HIST=~/z/update-hist.txt
printf "⌛️ ${C_B}Last Update: ${C_N}"
if [ -f $HIST ]; then
  tail -n 1 $HIST  # print last one line
else
  print "${C_R}No history file exists.${C_N}"
fi
runCmd "🍺" brew update
runCmd "🍻" brew upgrade
runCmd "🥂" brew cleanup
runCmd "🍷" brew doctor
runCmd "🍷" rustup update

~/z/dev/versions
runCmd "💧" "npm install -g npm@latest"
runCmd "💧" "yarn global upgrade"
runCmd "💧" "nvm install node --reinstall-packages-from=node"
date +"%H:%M:%S %m/%d/%Y" >> $HIST
