#!/bin/zsh
C_R='\e[0;31m'
C_G='\e[0;32m'
C_B='\e[0;34m'
C_Y='\e[0;33m'
C_N='\e[0m'

showV ()
{
  printf "${C_Y}$1 "

  if [ -z "${VC}" ]
  then
    printf "${C_G}Latest=${VL}"
  else
    printf "${C_N}${VC} "
    if [ -z "${VL}" ]
    then
      printf "${C_G}*"
    else
      if [ "${VC}" = "${VL}" ]
      then
        printf "${C_G}Latest"
      else
        printf "${C_G}${VL} ${C_R}New!"
      fi
    fi
  fi

  if [ -z $2 ]
  then
    print "${C_N}"
  else
    print " $2${C_N}"
  fi
}

print "${C_G}┌──────────┬───────────┬────────┐"
print "${C_G}│ ${C_Y}Versions${C_G} │ ${C_N}Installed${C_G} │ Latest │"
print "${C_G}└──────────┴───────────┴────────┘"
VC=`node -v`
VL="v`npm show node@lts version`"
showV "🍏 node    :"

VC=`npm -v`
VL=`npm show npm version`
showV "🎁 npm     :"

VC=`yarn -v`
VL=`npm show yarn version`
showV "🧶  yarn    :"

VC=`create-react-app --version`
VL=`npm show create-react-app version`
showV "🥐 CRA     :" "${C_B}# create-react-app"

VC=""
VL=`npm show react version`
showV "🍙 react   :"

VC=""
VL=`npm show react-scripts version`
showV "🍣 scripts :" "${C_B}# react-scripts"

VC=`ruby -v`
VL=""
showV "🔮 ruby    :"

VC=`python --version`
VL=""
showV "🐍 python  :"

VC=`pip3 --version`
VL=""
showV "🐢 pip     :"
print "${C_B}🦎 pip-check for further informationC_N}"

VC=`rustup --version`
VL=""
showV "💎 rustup  :"
VC=`rustc --version`
VL=""
showV "⚙️a rustc   :"

VC=`cargo --version`
VL=""
showV "📦 cargo   :"
